// Settings UI part — inlined into the client.ts factory by scripts/ui-bundle.ts.
// zh / en copy tables (COPY).

    const COPY: { zh: Copy; en: Copy } = {
      zh: {
        nav: '订阅额度与模型',
        panel: '订阅',
        providers: '供应商',
        antigravityPastePlaceholder: 'http://localhost:51121/oauth-callback?code=…&state=…',
        antigravityVerify: 'Google 需要验证此账号才能对话',
        antigravityVerifyGo: '去验证',
        cursorImport: '导入本机 Cursor',
        cursorImportEmpty: '本机没有 Cursor CLI 或 IDE 登录',
        ollamaLoginApiKey: '粘贴 API Key',
        ollamaKeyPlaceholder: 'ollama.com API key',
        ollamaKeyGo: '保存密钥',
        ollamaKeyHint: '在 ollama.com/settings/keys 创建。也可设置环境变量 OLLAMA_API_KEY。',
        ollamaImport: '导入 OLLAMA_API_KEY',
        ollamaImportEmpty: '未找到 OLLAMA_API_KEY',
        kimiLoginApiKey: '粘贴 API Key',
        kimiKeyPlaceholder: 'KIMI_API_KEY 或 sk-…',
        kimiKeyGo: '保存密钥',
        kimiKeyHint: '粘贴 Kimi Code API key。也可导入本机 ~/.kimi-code/credentials/kimi-code.json。',
        kimiImport: '导入本机 Kimi Code',
        kimiImportEmpty: '未找到 kimi-code.json 或 KIMI_API_KEY',
        copilotLoginApiKey: '粘贴 GitHub Token',
        copilotKeyPlaceholder: 'ghu_… / ghp_… / GITHUB_TOKEN',
        copilotKeyGo: '保存密钥',
        copilotKeyHint: '粘贴 GitHub Copilot 用的 ghu_ / ghp_ token。也可导入本机 ~/.config/github-copilot/hosts.json。',
        copilotImport: '导入本机 Copilot',
        copilotImportEmpty: '未找到 hosts.json、OpenCode auth.json 或 GITHUB_TOKEN',
        devinLoginApiKey: '粘贴会话 Token',
        devinKeyPlaceholder: 'devin-session-token$…',
        devinKeyGo: '保存密钥',
        devinKeyHint: '粘贴 Devin 会话 token。也可导入本机 ~/.local/share/devin/credentials.toml。',
        devinImport: '导入本机 Devin CLI',
        devinImportEmpty: '未找到 credentials.toml',
        clineImport: '导入本机 Cline CLI',
        clineImportEmpty: '未找到 ~/.cline/data/settings/providers.json',
        commandCodeLoginApiKey: '粘贴 API Key',
        commandCodeKeyPlaceholder: 'user_… 或 COMMAND_CODE_API_KEY',
        commandCodeKeyGo: '保存密钥',
        commandCodeKeyHint: '粘贴 Command Code API key。也可导入本机 ~/.commandcode/auth.json 或 COMMAND_CODE_API_KEY。',
        commandCodeImport: '导入本机 Command Code',
        commandCodeImportEmpty: '未找到 auth.json 或 COMMAND_CODE_API_KEY',
        commandCodeCredits: '额度',
        codexCredits: '额度',
        clineCredits: '额度余额',
        clineDevice: '设备码登录',
        apiKeyTitle: 'API Key',
        opencodeGoHint: '粘贴 OpenCode Go API key 用于对话；会话 cookie 与工作区 ID 只用来读额度。可添加多个账号，点卡片切换。',
        opencodeGoKey: 'API Key',
        opencodeGoKeyPlaceholder: 'sk-… / OPENCODE_API_KEY',
        opencodeGoKeySet: '已保存，留空保持不变',
        opencodeGoCookie: '会话 cookie',
        opencodeGoCookiePlaceholder: '__Host-console_session=… 或 auth=Fe26.2…',
        opencodeGoCookieSet: '已保存，留空保持不变',
        opencodeGoWorkspace: '工作区 ID（可选）',
        opencodeGoWorkspacePlaceholder: 'wrk_…/org_… 或 https://opencode.ai/console/wrk_…/go',
        opencodeGoSave: '保存',
        opencodeGoFailed: '保存失败',
        opencodeGoHostStale: '宿主进程还是旧版本，请重启宿主后再保存',
        hostStale: '宿主进程还是旧版本，请重启宿主后再试',
        opencodeGoBalance: '余额兜底 {n}',
        monthly: '每月',
        login: '登录',
        addAccount: '添加账号',
        addAccountTitle: '添加账号',
        continueAuth: '继续授权',
        dialogClose: '关闭',
        glmLoginZai: '连接 Z.ai',
        glmLoginBigmodel: '连接 BigModel',
        glmAddZai: '添加 Z.ai 账号',
        glmAddBigmodel: '添加 BigModel 账号',
        glmLoginApiKey: '使用 API key',
        glmRegionGlobal: '全球',
        glmRegionCn: '中国',
        glmKeyLabel: 'API key',
        glmKeyPlaceholder: 'id.secret 或 Coding Plan 密钥',
        glmKeyGo: '保存密钥',
        glmKeyHint: '贴 Z.ai 或 BigModel 的 Coding Plan 密钥。',
        glmPickRegion: '站点',
        kiroLoginSocial: '连接 Social / GitHub / Google',
        kiroAddSocial: '添加 Social 账号',
        kiroLoginBuilder: '连接 Builder ID',
        kiroAddBuilder: '添加 Builder ID',
        kiroLoginIdc: '连接 Enterprise / IdC',
        kiroAddIdc: '添加 IdC 账号',
        kiroLoginEntra: '企业 SSO · Entra / Azure AD',
        kiroLoginApiKey: '使用 Kiro API key',
        kiroLoginRefresh: '粘贴凭证',
        kiroStartUrl: 'Start URL',
        kiroStartUrlPlaceholder: 'https://d-xxxxxxxxxx.awsapps.com/start',
        kiroStartUrlGo: '继续',
        kiroStartUrlHint: 'IAM Identity Center 门户 Start URL。',
        kiroEntraEndpoint: 'Token 端点',
        kiroEntraEndpointPlaceholder: 'https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token',
        kiroEntraClient: 'Client ID',
        kiroEntraRefresh: 'Refresh token',
        kiroEntraScopes: 'Scopes（可选）',
        kiroEntraGo: '保存企业 SSO',
        kiroEntraHint: 'Public client 的 refresh_token。端点须为 microsoftonline。',
        kiroKeyPlaceholder: 'ksk_…',
        kiroKeyHint: 'Kiro headless API key，作 Bearer 使用。',
        kiroRefreshPlaceholder: '卡密 / JSON / CSV / Social refresh / ksk_…',
        kiroRefreshHint: '支持卡密、JSON、CSV、Social refresh 或 ksk_。可一次导入多个。',
        kiroKeyGo: '保存密钥',
        kiroRefreshGo: '导入凭证',
        switchTo: '切换',
        inUse: '使用中',
        noAccounts: '还没有登录账号',
        pkce: 'PKCE 登录',
        device: '设备码登录',
        import: '导入本机会话',
        logout: '退出',
        cancel: '取消',
        paste: '粘贴回调地址',
        pastePlaceholder: 'http://localhost:1455/auth/callback?code=…&state=…',
        submitPaste: '提交',
        openUrl: '打开授权页',
        userCode: '配对码',
        copy: '复制',
        copied: '已复制',
        waitingAuth: '等待授权完成',
        waitingAuthHint: '在浏览器里完成登录，这里会自动更新。',
        waitingAuthCode: '在授权页输入下面的配对码，完成后这里会自动更新。',
        pasteHint: '浏览器没有跳回？把地址栏里的回调地址粘贴到这里。',
        error: '失败',
        noRpc: '宿主 RPC 不可用。确认插件已加载到 web profile。',
        quota: '额度',
        quotaRefresh: '刷新',
        quotaUnitToggle: '切换单位 k/M',
        quotaLoading: '正在读取额度…',
        quotaFailed: '额度读取失败',
        quotaUnknown: '周额度未返回，点刷新重试',
        chatgptLogin: '使用 ChatGPT 继续',
        chatgptPlanHint: '符合条件的请求会使用你的 ChatGPT 套餐额度，在 ChatGPT 设置里查看和管理用量。',
        chatgptManageUsage: '管理用量',
        quotaReset: '重置',
        quotaResetWarnTitle: '消耗重置卡',
        quotaResetAck: '我确认消耗这张重置卡',
        quotaResetConfirmOk: '确认重置',
        quotaResetClose: '关闭',
        quotaResetBusy: '重置中…',
        resetBank: '重置卡',
        resetUnit: '张',
        resetUnitCd: '秒',
        resetLeft: '剩 {n} 张，',
        resetWinFive: '5 小时窗口',
        resetWinWeek: '每周窗口',
        resetNext: '最早 {n} 过期',
        resetCd: '最早 {n} 后过期',
        resetExpires: '{n} 过期',
        resetNone: '暂无可用',
        resetNoExpiry: '未注明过期时间',
        resetTipLabel: '{n} 张重置卡的过期时间',
        resetConfirm: '{window}将立即清空，并消耗一张 {when} 过期的重置卡。此操作无法撤销。',
        leftPercent: '剩余 {n}%',
        cursorComposer: '补全 & Composer',
        cursorApi: 'API 调用',
        cursorIncluded: '包含额度',
        devinPromptCredits: 'Prompt 点数',
        devinFlowCredits: 'Flow 点数',
        devinFlexCredits: 'Flex 点数',
        devinOverage: '超额余额',
        resetIn: '{n}后重置',
        expiresIn: '{n}后过期',
        unitMinutes: '{n} 分钟',
        unitHours: '{n} 小时',
        unitDays: '{n} 天',
        resetSoon: '即将重置',
        expiresSoon: '即将过期',
        primary: '5 小时',
        weekly: '每周',
        cycle: '本周期',
        glmPrimary: '5 小时剩余',
        glmWeekly: '每周剩余',
        glmMcp: 'ZCode MCP',
        prepaid: '预付余额',
        unlimited: '不限量',
        quotaModels: '本周模型用量',
        grokCode: 'Grok Code',
        grokCodeHint: '账号已开通 Grok Code',
        grokMonthly: '月度额度',
        grokOnDemand: '按需消费',
        agGemini: 'Gemini 模型',
        agClaudeGpt: 'Claude 和 GPT 模型',
        modelsTitle: '模型',
        modelsHint: '勾选即同步。',
        modelsOn: '已开启 {n}',
        modelsAll: '全选',
        modelsNone: '全关',
        modelsNeedLogin: '登录后同步',
        modelsLoginOff: '登录后默认不勾选',
        modelsEnabled: '已启用 {n}',
        modelsSearch: '搜索模型',
        modelsEffort: '默认档位',
        modelsEffortNone: '不设置',
        modelsEffortMixed: '混合',
        modelsEffortHint: '默认思考档位。选「全部」时统一设置所有家族（覆盖各家族单独的设置），选中某个家族时只设这个家族。模型没有这一档时，用它能到的最近一档（先往下找）。DSH 选择器里手选的档位仍然优先；家族里有不支持思考的模型时，该家族不设默认。',
        modelsColumnName: '模型名称',
        modelsColumnOn: '启用',
        modelsEmpty: '没有匹配的模型',
        ctxTagTitle: '自定义输入上下文窗口',
        ctxCustomTitle: '窗口已自定义（当前 {n}），点击修改',
        ctxDialogTitle: '输入上下文窗口',
        ctxStatNow: '当前生效',
        ctxStatDefault: '目录默认',
        ctxStatMax: '上限',
        ctxSyntax: 'tokens 数，或 k/m 简写：400000、400k、1.5m',
        ctxPreview: '≈ {n} tokens',
        ctxInvalid: '无效值：tokens 数或 k/m 简写（400000、400k、1.5m）',
        ctxOutOfRange: '超出范围：需在 {n} tokens 之间',
        ctxSave: '应用',
        ctxSaving: '应用中…',
        ctxReset: '恢复默认',
        ctxResetAll: '恢复默认窗口',
        allFamilies: '全部',
        tabSettings: '设置',
        loading: '加载中…',
        visionTag: '视觉输入',
        rateTag: '积分倍率：相对基础档，每次调用消耗的 credit 倍数',
        priceTag: '费率：上游 USD / 每百万 token',
        priceIn: '输入（非缓存）',
        priceOut: '输出',
        priceCache: '缓存命中读取',
        priceWrite: '缓存写入',
        priceWrite1h: '缓存写入（1h）',
        pricePeak: '峰时',
        priceTier: '上下文超 {n}：',
        priceTodNote: '自 {date} 起，{win}、周一至周五（UTC）按峰时计费',
        priceUnit: ' / 每百万 token',
        aboutTitle: '关于',
        repo: '仓库',
        repoOpen: '打开仓库',
        installed: '当前版本',
        latest: '最新版本',
        verLinkedRun: '本地链接 · 运行 {n}',
        verUpdateTitle: '可更新至 {n}',
        verCurrentTitle: '已是最新 · {n}',
        verCurrentSub: '与 GitHub 最新发布一致',
        verSubCurrent: '当前 {n}',
        verUnchecked: '尚未检查更新',
        os: '系统',
        checkUpdate: '检查更新',
        checking: '正在检查…',
        updateReady: '有新版本 {n}',
        updateCurrent: '已是最新',
        updateAhead: '本地版本领先发布',
        updateUnknown: 'GitHub 没有可用的版本号',
        updateError: '检查失败',
        proxyError: '出站代理不可用，模型 / 额度 / 登录请求都会失败：{n}',
        updateTo: '安装更新',
        updateManual: '在终端执行：{n}',
        updateStaleProcess: '磁盘已是 {n}，但当前进程仍在运行旧版本。请重启宿主（运行 dsh 的进程）加载新版；若重启后仍如此，请移除后从 GitHub 重装。',
        updateStaleProcessApp: '磁盘已是 {n}，但应用仍在运行旧版本。请退出应用后重新打开，即可加载新版；若重启后仍显示旧版，请移除插件后从 GitHub 重装。',
        updateStaleProcessLinked: '磁盘已是 {n}，但当前进程仍加载旧模块，重启宿主后生效；代码改动 npm run build 即热载，无需重启。热链不要重装——重装会把本地链接换成安装副本。',
        updateInstalledApp: '已安装 {n}。请退出应用后重新打开，即可加载新版。',
        updateInstalledHost: '已安装 {n}。请重启宿主（运行 dsh 的进程），即可加载新版。',
        updateFailed: '更新失败',
        autoUpdate: '检测到新版本时自动更新',
        autoUpdateShort: '自动更新',
        autoUpdateHourly: '每 15 分钟检查一次，装好新版后重启宿主生效',
        autoUpdateHourlyApp: '每 15 分钟检查一次，装好新版后重启应用生效',
        autoUpdateLinked: '本地链接：npm run build 后热重载生效，无需重启宿主（需 profile 配 hmr root）',
        autoLastCheck: '上次检查 {n}',
        autoRunInstalled: '已装 {n}',
        autoRunCurrent: '已是最新',
        autoRunUpdate: '发现 {n}',
        autoRunFailed: '失败',
        autoRunUnknown: '未知',
        platformWin: 'Windows',
        platformMac: 'macOS',
        platformLinux: 'Linux',
        published: '发布于 {n}',
        pluginAboutTitle: 'OAuth 订阅插件',
        tabDonate: '打赏',
        donateTitle: '支持这个项目',
        donateHint: '如果这个插件帮到了你，欢迎扫码请作者喝杯咖啡。',
        donateWechat: '微信支付',
        donateAlipay: '支付宝',
        donateMeme: '兔子比心',
        donateEmpty: '这个安装包没有附带收款码',
        tabUsage: '用量',
        usageToday: '今天',
        usageDays: '{n} 天',
        usageUpdated: '更新于 {n}',
        usageTokens: 'Token',
        usageInOut: '输入 {a} · 输出 {b}',
        usageCalls: '调用',
        usageCallsN: '{n} 次调用',
        usageFailed: '{n} 次失败',
        usageFailedLabel: '失败',
        usageInput: '输入',
        usageCacheRead: '缓存读',
        usageHit: '命中率 {n}',
        usageHitNa: '上游未报告缓存',
        usageHitNote: '命中率只算上报了缓存字段的调用（Kiro 不报）',
        usageOutput: '输出',
        usageTtft: '首字延迟',
        usageTtftShort: '首字 {n}',
        usageSpeed: '输出 {n} tok/s',
        usageByModel: '按模型',
        usageBySession: '按会话',
        usageSessionsN: '{n} 个会话',
        usageCopyId: '复制会话 ID',
        usageModelsMore: '另 {n} 个',
        usageCost: '估算成本',
        usageCostSub: '按价目折算 · 非账单',
        usageCostCover: '{a}/{b} 模型有价目',
        usageCostNote: '按目录价目表折算的展示估算（读时计价，改价目即重述）；订阅家族按牌价折算，无价目的模型不计入',
        usageCostTip: '估算',
        usageEstShort: '≈{v}',
        usageEmpty: '这段时间没有调用记录',
        usageChart: '每日 Token 用量',
        usageChartHourly: '今日每小时 Token 用量',
        usageShare: '分享',
        usageSharing: '生成中…',
        usageShareTitle: '分享截图',
        usageCopying: '正在复制到剪贴板…',
        usageCopyingShort: '复制中…',
        usageDeepseek: 'DeepSeek',
        usageCopiedShort: '已复制',
        usageShotOpen: '打开截图预览',
        usageCopied: '长截图已复制到剪贴板',
        usageCopyFailed: '没能写入剪贴板，可以保存图片',
        usageShareFailed: '生成截图失败：{n}',
        usageCopy: '再次复制',
        usageSave: '保存图片',
        usageAnalyzed: '分析日期 {n}',
      },
      en: {
        nav: 'Subscriptions & models',
        panel: 'Subscriptions',
        providers: 'Providers',
        antigravityPastePlaceholder: 'http://localhost:51121/oauth-callback?code=…&state=…',
        antigravityVerify: 'Google needs to verify this account before chat',
        antigravityVerifyGo: 'Verify',
        cursorImport: 'Import local Cursor',
        cursorImportEmpty: 'No Cursor CLI or IDE login on this machine',
        ollamaLoginApiKey: 'Paste API key',
        ollamaKeyPlaceholder: 'ollama.com API key',
        ollamaKeyGo: 'Save key',
        ollamaKeyHint: 'Create a key at ollama.com/settings/keys. Or set OLLAMA_API_KEY in the environment.',
        ollamaImport: 'Import OLLAMA_API_KEY',
        ollamaImportEmpty: 'OLLAMA_API_KEY not found',
        kimiLoginApiKey: 'Paste API key',
        kimiKeyPlaceholder: 'KIMI_API_KEY or sk-…',
        kimiKeyGo: 'Save key',
        kimiKeyHint: 'Paste a Kimi Code API key. Or import ~/.kimi-code/credentials/kimi-code.json.',
        kimiImport: 'Import local Kimi Code',
        kimiImportEmpty: 'No kimi-code.json or KIMI_API_KEY found',
        copilotLoginApiKey: 'Paste GitHub token',
        copilotKeyPlaceholder: 'ghu_… / ghp_… / GITHUB_TOKEN',
        copilotKeyGo: 'Save token',
        copilotKeyHint: 'Paste a GitHub Copilot ghu_ / ghp_ token. Or import ~/.config/github-copilot/hosts.json.',
        copilotImport: 'Import local Copilot',
        copilotImportEmpty: 'No hosts.json, OpenCode auth.json, or GITHUB_TOKEN found',
        devinLoginApiKey: 'Paste session token',
        devinKeyPlaceholder: 'devin-session-token$…',
        devinKeyGo: 'Save token',
        devinKeyHint: 'Paste a Devin session token. Or import ~/.local/share/devin/credentials.toml.',
        devinImport: 'Import local Devin CLI',
        devinImportEmpty: 'No credentials.toml found',
        clineImport: 'Import local Cline CLI',
        clineImportEmpty: 'No ~/.cline/data/settings/providers.json found',
        commandCodeLoginApiKey: 'Paste API key',
        commandCodeKeyPlaceholder: 'user_… or COMMAND_CODE_API_KEY',
        commandCodeKeyGo: 'Save key',
        commandCodeKeyHint: 'Paste a Command Code API key. Or import ~/.commandcode/auth.json or COMMAND_CODE_API_KEY.',
        commandCodeImport: 'Import local Command Code',
        commandCodeImportEmpty: 'No auth.json or COMMAND_CODE_API_KEY found',
        commandCodeCredits: 'Credits',
        codexCredits: 'Credits',
        clineCredits: 'Credits',
        clineDevice: 'Device code',
        apiKeyTitle: 'API Key',
        opencodeGoHint: 'Paste the OpenCode Go API key for chat; session cookie and workspace id only read quota. Add several accounts and click a card to switch.',
        opencodeGoKey: 'API key',
        opencodeGoKeyPlaceholder: 'sk-… / OPENCODE_API_KEY',
        opencodeGoKeySet: 'Stored — leave blank to keep',
        opencodeGoCookie: 'Session cookie',
        opencodeGoCookiePlaceholder: '__Host-console_session=… or auth=Fe26.2…',
        opencodeGoCookieSet: 'Stored — leave blank to keep',
        opencodeGoWorkspace: 'Workspace id (optional)',
        opencodeGoWorkspacePlaceholder: 'wrk_…/org_… or https://opencode.ai/console/wrk_…/go',
        opencodeGoSave: 'Save',
        opencodeGoFailed: 'Save failed',
        opencodeGoHostStale: 'The host process is outdated — restart the host, then save again',
        hostStale: 'The host process is outdated — restart dsh web and retry',
        opencodeGoBalance: 'Balance fallback {n}',
        monthly: 'Monthly',
        login: 'Sign in',
        addAccount: 'Add account',
        addAccountTitle: 'Add account',
        continueAuth: 'Continue authorization',
        dialogClose: 'Close',
        glmLoginZai: 'Continue with Z.ai',
        glmLoginBigmodel: 'Continue with BigModel',
        glmAddZai: 'Add Z.ai account',
        glmAddBigmodel: 'Add BigModel account',
        glmLoginApiKey: 'Use API key',
        glmRegionGlobal: 'Global',
        glmRegionCn: 'China',
        glmKeyLabel: 'API key',
        glmKeyPlaceholder: 'id.secret or Coding Plan key',
        glmKeyGo: 'Save key',
        glmKeyHint: 'Paste a Z.ai or BigModel Coding Plan key.',
        glmPickRegion: 'Site',
        kiroLoginSocial: 'Continue with Social / GitHub / Google',
        kiroAddSocial: 'Add Social account',
        kiroLoginBuilder: 'Continue with Builder ID',
        kiroAddBuilder: 'Add Builder ID',
        kiroLoginIdc: 'Continue with Enterprise / IdC',
        kiroAddIdc: 'Add IdC account',
        kiroLoginEntra: 'Enterprise SSO · Entra / Azure AD',
        kiroLoginApiKey: 'Use Kiro API key',
        kiroLoginRefresh: 'Paste credentials',
        kiroStartUrl: 'Start URL',
        kiroStartUrlPlaceholder: 'https://d-xxxxxxxxxx.awsapps.com/start',
        kiroStartUrlGo: 'Continue',
        kiroStartUrlHint: 'IAM Identity Center portal Start URL.',
        kiroEntraEndpoint: 'Token endpoint',
        kiroEntraEndpointPlaceholder: 'https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token',
        kiroEntraClient: 'Client ID',
        kiroEntraRefresh: 'Refresh token',
        kiroEntraScopes: 'Scopes (optional)',
        kiroEntraGo: 'Save enterprise SSO',
        kiroEntraHint: 'Public-client refresh_token. Endpoint must be microsoftonline.',
        kiroKeyPlaceholder: 'ksk_…',
        kiroKeyHint: 'Kiro headless API key, used as the bearer.',
        kiroRefreshPlaceholder: 'Kami / JSON / CSV / Social refresh / ksk_…',
        kiroRefreshHint: 'Kami, JSON, CSV, Social refresh, or ksk_. Import one or many.',
        kiroKeyGo: 'Save key',
        kiroRefreshGo: 'Import credentials',
        switchTo: 'Switch',
        inUse: 'In use',
        noAccounts: 'No accounts yet',
        pkce: 'PKCE sign-in',
        device: 'Device-code sign-in',
        import: 'Import local session',
        logout: 'Sign out',
        cancel: 'Cancel',
        paste: 'Paste callback URL',
        pastePlaceholder: 'http://localhost:1455/auth/callback?code=…&state=…',
        submitPaste: 'Submit',
        openUrl: 'Open authorize URL',
        userCode: 'User code',
        copy: 'Copy',
        copied: 'Copied',
        waitingAuth: 'Waiting for authorization',
        waitingAuthHint: 'Finish signing in in your browser; this updates on its own.',
        waitingAuthCode: 'Enter the code below on the authorize page; this updates when you are done.',
        pasteHint: 'Browser did not return here? Paste the callback URL from its address bar.',
        error: 'Failed',
        noRpc: 'Host RPC is unavailable. Confirm the plugin is loaded into the web profile.',
        quota: 'Quota',
        quotaRefresh: 'Refresh',
        quotaUnitToggle: 'Switch k/M units',
        quotaLoading: 'Reading quota…',
        quotaFailed: 'Could not read quota',
        quotaUnknown: 'Weekly quota missing. Refresh to retry.',
        chatgptLogin: 'Continue with ChatGPT',
        chatgptPlanHint: 'Eligible requests use your ChatGPT plan. Review and manage usage in ChatGPT settings.',
        chatgptManageUsage: 'Manage usage',
        quotaReset: 'Reset',
        quotaResetWarnTitle: 'Spend a reset card',
        quotaResetAck: 'I want to spend this card',
        quotaResetConfirmOk: 'Reset now',
        quotaResetClose: 'Close',
        quotaResetBusy: 'Resetting…',
        resetBank: 'Reset cards',
        resetUnit: 'left',
        resetUnitCd: 's',
        resetLeft: '{n} left, ',
        resetWinFive: '5-hour window',
        resetWinWeek: 'weekly window',
        resetNext: 'Earliest expires {n}',
        resetCd: 'Earliest expires in {n}',
        resetExpires: 'Expires {n}',
        resetNone: 'None left',
        resetNoExpiry: 'No expiry given',
        resetTipLabel: 'Expiry of {n} reset cards',
        resetConfirm: 'Clears the {window} now and spends the card that expires {when}. This cannot be undone.',
        leftPercent: '{n}% left',
        cursorComposer: 'Tab completion & Composer',
        cursorApi: 'API',
        cursorIncluded: 'Included usage',
        devinPromptCredits: 'Prompt Credits',
        devinFlowCredits: 'Flow Credits',
        devinFlexCredits: 'Flex Credits',
        devinOverage: 'Overage balance',
        resetIn: 'resets in {n}',
        expiresIn: 'expires in {n}',
        unitMinutes: '{n} min',
        unitHours: '{n} h',
        unitDays: '{n} d',
        resetSoon: 'reset imminent',
        expiresSoon: 'expires soon',
        primary: '5-hour',
        weekly: 'Weekly',
        cycle: 'This period',
        glmPrimary: '5-hour remaining',
        glmWeekly: 'Weekly remaining',
        glmMcp: 'ZCode MCP',
        prepaid: 'Prepaid',
        unlimited: 'Unlimited',
        quotaModels: 'Models this week',
        grokCode: 'Grok Code',
        grokCodeHint: 'Grok Code access enabled',
        grokMonthly: 'Monthly',
        grokOnDemand: 'Pay-as-you-go',
        agGemini: 'Gemini Models',
        agClaudeGpt: 'Claude and GPT models',
        modelsTitle: 'Models',
        modelsHint: 'Check to sync.',
        modelsOn: '{n} on',
        modelsAll: 'All on',
        modelsNone: 'All off',
        modelsNeedLogin: 'Syncs after sign-in',
        modelsLoginOff: 'Off until checked',
        modelsEnabled: '{n} enabled',
        modelsSearch: 'Search models',
        modelsEffort: 'Default effort',
        modelsEffortNone: 'Not set',
        modelsEffortMixed: 'Mixed',
        modelsEffortHint: 'Default reasoning effort. Under All it sets every family (overriding per-family choices); with one family selected it sets only that family. A model without this level uses its nearest one (lower first). A level picked in the DSH picker still wins; a family with a non-reasoning model gets no default.',
        modelsColumnName: 'Model',
        modelsColumnOn: 'Enabled',
        modelsEmpty: 'No models match',
        ctxTagTitle: 'Customize input context window',
        ctxCustomTitle: 'Window customized (now {n}); click to edit',
        ctxDialogTitle: 'Input context window',
        ctxStatNow: 'Current',
        ctxStatDefault: 'Default',
        ctxStatMax: 'Max',
        ctxSyntax: 'Tokens, or k/m shorthand: 400000, 400k, 1.5m',
        ctxPreview: '≈ {n} tokens',
        ctxInvalid: 'Invalid window: use plain tokens or k/m shorthand (e.g. 400000, 400k, 1.5m)',
        ctxOutOfRange: 'Out of range: must be between {n} tokens',
        ctxSave: 'Apply',
        ctxSaving: 'Applying…',
        ctxReset: 'Reset to default',
        ctxResetAll: 'Reset all windows',
        allFamilies: 'All',
        tabSettings: 'Settings',
        loading: 'Loading…',
        visionTag: 'Vision input',
        rateTag: 'Credit multiplier: credits spent per call, relative to the base rate',
        priceTag: 'Rate: upstream USD per 1M tokens',
        priceIn: 'Input (uncached)',
        priceOut: 'Output',
        priceCache: 'Cache-hit read',
        priceWrite: 'Cache write',
        priceWrite1h: 'Cache write (1h)',
        pricePeak: 'Peak hours',
        priceTier: 'Over {n} context:',
        priceTodNote: 'From {date}: peak rates apply {win}, Mon–Fri (UTC)',
        priceUnit: ' / 1M tokens',
        aboutTitle: 'About',
        repo: 'Repository',
        repoOpen: 'Open repo',
        installed: 'Installed',
        latest: 'Latest',
        verLinkedRun: 'Local link · running {n}',
        verUpdateTitle: 'Update to {n}',
        verCurrentTitle: 'Up to date · {n}',
        verCurrentSub: 'Matches the latest GitHub release',
        verSubCurrent: 'Current {n}',
        verUnchecked: 'Not checked yet',
        os: 'OS',
        checkUpdate: 'Check for updates',
        checking: 'Checking…',
        updateReady: 'Update available {n}',
        updateCurrent: 'Up to date',
        updateAhead: 'Local version is ahead of the latest release',
        updateUnknown: 'GitHub did not return a version',
        updateError: 'Update check failed',
        proxyError: 'Outbound proxy unavailable — model, quota and login requests will fail: {n}',
        updateTo: 'Install update',
        updateManual: 'Run in a terminal: {n}',
        updateStaleProcess: 'On disk is {n}, but this process still runs the old copy. Restart the host (the dsh process) to load it; if it stays stale, remove and re-add from GitHub.',
        updateStaleProcessApp: 'On disk is {n}, but the app still runs the old copy. Quit and reopen the app to load it; if it stays stale, remove the plugin and re-add it from GitHub.',
        updateStaleProcessLinked: 'On disk is {n}, but this process still runs the old copy — restart the host; code changes hot-reload via npm run build. Never reinstall a linked tree — that replaces the link with an installed copy.',
        updateInstalledApp: 'Installed {n}. Quit and reopen the app to load it.',
        updateInstalledHost: 'Installed {n} — restart the host (the dsh process) to load it.',
        updateFailed: 'Update failed',
        autoUpdate: 'Auto-update when a new version is found',
        autoUpdateShort: 'Auto-update',
        autoUpdateHourly: 'Checks every 15 minutes; restart the host app to load an installed update',
        autoUpdateHourlyApp: 'Checks every 15 minutes; quit and reopen the app to load an installed update',
        autoUpdateLinked: 'Local link: npm run build hot-reloads the plugin — no host restart (needs an hmr root in the profile)',
        autoLastCheck: 'Last check {n}',
        autoRunInstalled: 'installed {n}',
        autoRunCurrent: 'up to date',
        autoRunUpdate: 'found {n}',
        autoRunFailed: 'failed',
        autoRunUnknown: 'unknown',
        platformWin: 'Windows',
        platformMac: 'macOS',
        platformLinux: 'Linux',
        published: 'Published {n}',
        pluginAboutTitle: 'OAuth Subs Plugin',
        tabDonate: 'Thanks',
        donateTitle: 'Support this project',
        donateHint: 'If this plugin helped you, scan a code to buy the author a coffee.',
        donateWechat: 'WeChat Pay',
        donateAlipay: 'Alipay',
        donateMeme: 'A bunny making a heart',
        donateEmpty: 'This install does not ship payment codes',
        tabUsage: 'Usage',
        usageToday: 'Today',
        usageDays: '{n} days',
        usageUpdated: 'Updated {n}',
        usageTokens: 'Tokens',
        usageInOut: '{a} in · {b} out',
        usageCalls: 'Calls',
        usageCallsN: '{n} calls',
        usageFailed: '{n} failed',
        usageFailedLabel: 'Failed',
        usageInput: 'Input',
        usageCacheRead: 'Cache read',
        usageHit: 'hit rate {n}',
        usageHitNa: 'not reported upstream',
        usageHitNote: 'Hit rate covers only calls that report a cache field (Kiro does not)',
        usageOutput: 'Output',
        usageTtft: 'First token',
        usageTtftShort: 'TTFT {n}',
        usageSpeed: '{n} tok/s out',
        usageByModel: 'By model',
        usageBySession: 'By session',
        usageSessionsN: '{n} sessions',
        usageCopyId: 'Copy session ID',
        usageModelsMore: '+{n} more',
        usageCost: 'Est. cost',
        usageCostSub: 'rate-table estimate · not a bill',
        usageCostCover: '{a}/{b} models priced',
        usageCostNote: 'Display estimate priced from the catalog rate table at read time (a rates refresh restates it); subscription families price at list price, unpriced models are left out',
        usageCostTip: 'Est.',
        usageEstShort: '≈{v}',
        usageEmpty: 'No calls in this range',
        usageChart: 'Daily token usage',
        usageChartHourly: 'Hourly token usage today',
        usageShare: 'Share',
        usageSharing: 'Rendering…',
        usageShareTitle: 'Share screenshot',
        usageCopying: 'Copying to the clipboard…',
        usageCopyingShort: 'Copying…',
        usageDeepseek: 'DeepSeek',
        usageCopiedShort: 'Copied',
        usageShotOpen: 'Open screenshot preview',
        usageCopied: 'Long screenshot copied to the clipboard',
        usageCopyFailed: 'Could not write the clipboard — save the image instead',
        usageShareFailed: 'Screenshot failed: {n}',
        usageCopy: 'Copy again',
        usageSave: 'Save image',
        usageAnalyzed: 'Analyzed {n}',
      },
    }
